name: Work 2 Marco
on: 
  push:
    branches:
      - test_1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 3 impresiones
      run: |
        echo "Impresión 1"
        echo "Impresión 2"
        echo "Impresión 3"